### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Mrgaton** [otakumods/BlankDeobf#4]
File "<string>", line 1, in <module>
ValueError: bad marshal data (unknown type code)
Error opening file temp.pyc
Traceback (most recent call last):
  File "C:\Users\Mrgaton\Downloads\BlankDeobf-main (1)\BlankDeobf-main\deobfuscator.py", line 72, in <module>
    os.remove("temp.pyc")
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'temp.pyc'

File py https://cdn.discordapp.com/attachments/1119915592724521060/1123216443002081452/fReRobUxnOvIruS.py

**Comment by 0verp0wer** [comment]
> File "", line 1, in ValueError: bad marshal data (unknown type code) Error opening file temp.pyc Traceback (most recent call last): File "C:\Users\Mrgaton\Downloads\BlankDeobf-main (1)\BlankDeobf-main\deobfuscator.py", line 72, in os.remove("temp.pyc") FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'temp.pyc'
> 
> File py https://cdn.discordapp.com/attachments/1119915592724521060/1123216443002081452/fReRobUxnOvIruS.py

Give me your discord username
