### ISSUE TITLE
didnt work

### ISSUE THREAD

**Issue by Phxnt0mWare** [otakumods/BlankDeobf#5]
python: can't open file 'C:\\Users\\lmfao\\Downloads\\BlankDeobf-main\\BlankDeobf-main\\components\\writeconfig.pyw': [Errno 2] No such file or directory
Error opening file temp.pyc
Traceback (most recent call last):
  File "C:\Users\lmfao\Downloads\BlankDeobf-main\BlankDeobf-main\deobfuscator.py", line 71, in <module>
    os.remove("temp.pyc")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'temp.pyc'
PS C:\Users\lmfao\Downloads\BlankDeobf-main\BlankDeobf-main>

**Comment by otakumods** [comment]
> python: can't open file 'C:\Users\lmfao\Downloads\BlankDeobf-main\BlankDeobf-main\components\writeconfig.pyw': [Errno 2] No such file or directory Error opening file temp.pyc Traceback (most recent call last): File "C:\Users\lmfao\Downloads\BlankDeobf-main\BlankDeobf-main\deobfuscator.py", line 71, in os.remove("temp.pyc") FileNotFoundError: [WinError 2] The system cannot find the file specified: 'temp.pyc' PS C:\Users\lmfao\Downloads\BlankDeobf-main\BlankDeobf-main>

Dm me on discord over_on_top
